//Splashtexts (free to edit!)
const splashText = [
	"Welcome. Welcome to City 17.",
	"The perfect dog...",
	"Avonya is here sometimes!",
	"OH MY GOD WE'RE DOOOMMMEDD",
	"I AM NOT A MORON",
	"Apple.",
	"Say apple, apple.",
	"My clone!",
	"Ah, hello gordon!",
	"there's nothing there.",
	"FEED ME MY COOOOIINNSNS MR FREEMMANNNN",
	"Are you still there?",
	"Don't shoot! I'm with the science team!",
	"Don't shoot, I'm the one man that knows EVERYTHING",
	"It wasn't meant to do this in the first place..",
	"hey do you have your passport?",
	"It seems the containment system has COMPLETELY failed.",
	"This is all because of YOU SCIENTISTS",
	"Hey, catch me later I'll buy you a beer.",
	"Pick me up!",
	"Put me down!",
	"Hahe!",
	"Sbarros tommorow, quiznos today!",
	"Drink the sodaa, it'll make you see fasterrr!!",
	"Look gordon, ropes! We can use these for big pits!",
	"darnald",
	"We've assured the administrator that NOTHING will go wrong.",
	"It's showing a small discrepency in - well no, it's well in acceptable bounds again. Sustaining sequence.",
	"I did have a wife, but they took her in the divorce.",
	"DON'T MESS WITH THE SCIENNCEE TEAMMM",
	"Nothing ventured, nothing gained!",
	"I read about this on Wikipedia, the FREE online encyclopedia that ANYONE can edit!",
	"Is it bigger than a breadbox?",
	"Good news everyone!",
	"Meow",
	"What cat?",
	"PK FIRE!",
	'PK THUNDER!',
	'PK SANDSTORM!',
	'Need a hand?',
	'Target acquired',
	'I see you',
	'Intervention? Intervention? Intervention?',
	'Sentry mode activated',
	'Ha ha, caught another one!',
	'Sorry, I\'m on duty, Mr. Freeman.',
	':3',
	'Hey, Mr. Freeman, I had a bunch of messages for you but we had a system crash about 20 minutes ago and I\'m still trying to find my files. Just one of those days I guess. They were having some problems down in the test chamber too, but I think that\'s all straightened out. They told me to make sure you headed down there as soon as you got into your hazard suit.',
	'Good morning and welcome to the Black Mesa Transit system',
	"Welcome to Half-Life 2, Episode 2. We are at the mid-point in our trilogy of episodes which will conclude in Episode 3. To listen to a commentary node, put your crosshair over the floating commentary symbol and press your use key. To stop a commentary node, put your crosshair over the rotating node and press the use key again. Some commentary nodes may take control of the game in order to show something to you. In these cases, simply  press your use key again to stop the commentary. Please let me know what you think after you've had a chance to play this. I can be reached at gaben@valvesoftware.com, I get about 10,000 emails each time we release a game, and while I can't respond to all of them, I do read all of them. Thanks, and have fun!",
	'Alt+] or alt+u selects an image, alt+] or alt+i sends the image',
	'Pressing period when the textbox is not selected toggles autoscroll',
	"I don't even know whose peanut butter it was! I was hungry and there was peanut butter!",
	"15 Seconds of Bora! (YEAH!)",
	"Maybe the real Bad Place were the friends we made along the way.",
	"Bortles!",
	"Oh dip!",
	"My name is Zubin and I can swim!!!",
	"Hit the whip!",
	"It's peanut butter jelly time!",
	"This sentence is false.",
	"So there's this man, he has a time machine. Up and down history he goes, zip, zip, zip, zip, zip, getting into scrapes. Another thing he has is a a passion for the works of Ludwig van Beethoven. And one day he thinks, 'What's the point of having a time machine if you don't get to meet your heroes?' So off he goes to 18th century Germany, but he can't find Beethoven anywhere. No one's heard of him. Not even his family have any idea who the time traveller is talking about. Beethoven literally... doesn't exist. This didn't happen by the way. I've met Beethoven. Nice chap, very intense. Loved an arm wrestle. No, this is called the bootstrap paradox. Google it. The time traveller panics. He can't bear the thought of a world without the music of Beethoven. Luckily he brought all of his Beethoven sheet music for Ludwig to sign. So he copies out all the concertos and the symphonies, and he gets them published. He becomes Beethoven. And history continues with barely a feather ruffled. But my question is this - who put those notes and phrases together? Who really composed Beethoven's 5th?",
  "Don't forget to click below to subscribe to the official Doctor Who YouTube channel",
	`${Math.floor(Math.random() * 10000)} is your lucky number`,
	"I might rap like an english chap",
	"Hey ho, don't cha know, it's a good old fashion puppet show, thats right quite the set, it's the marionette quintet",
	"Ah, Hello Gordon!",
	"Another day another dollar!", //thats what we say here at the black mesa research facility! Ha ha!
	"I drink soda for lunch",
	"Why do we have to all wear these ridiculous ties?!",
	"Do you know who ate all the donuts?",
	"Have you seen my coffee cup?",
  "Stop fucking with the microwave!",
  '"Who is Gordon?" - Rey',
  'Part one.',
  'Part two.',
  'Part three.',
	
];
function refreshSplash(){
	//Display the splashtext
	textBox.placeholder = splashText[Math.floor(Math.random() * splashText.length)];
}
refreshSplash();