//Splashtexts (free to edit!)
const splashText = [
	"Welcome. Welcome to City 17.",
	"The perfect dog...",
	"Avonya is here sometimes!",
	"OH MY GOD WE'RE DOOOMMMEDD",
	"I AM NOT A MORON",
	"Apple.",
	"Say apple, apple.",
	"My clone!",
	"Ah, hello gordon!",
	"there's nothing there.",
	"FEED ME MY COOOOIINNSNS MR FREEMMANNNN",
	"Are you still there?",
	"Don't shoot! I'm with the science team!",
	"Don't shoot, I'm the one man that knows EVERYTHING",
	"It wasn't meant to do this in the first place..",
	"hey do you have your passport?",
	"It seems the containment system has COMPLETELY failed.",
	"This is all because of YOU SCIENTISTS",
	"Hey, catch me later I'll buy you a beer.",
	"Pick me up!",
	"Put me down!",
	"Hahe!",
	"Sbarros tommorow, quiznos today!",
	"Drink the sodaa, it'll make you see fasterrr!!",
	"Look gordon, ropes! We can use these for big pits!",
	"darnald",
	"We've assured the administrator that NOTHING will go wrong.",
	"It's showing a small discrepency in - well no, it's well in acceptable bounds again. Sustaining sequence.",
	"I did have a wife, but they took her in the divorce.",
	"DON'T MESS WITH THE SCIENNCEE TEAMMM",
	"Nothing ventured, nothing gained!",
	"I read about this on Wikipedia, the FREE online encyclopedia that ANYONE can edit!",
	"Is it bigger than a breadbox?",
	"Good news everyone!",
	"Meow",
	"What cat?",
	"PK FIRE!",
	'PK THUNDER!',
	'PK SANDSTORM!',
	'Need a hand?',
	'Target acquired',
	'I see you',
	'Intervention? Intervention? Intervention?',
	'Sentry mode activated',
	'Ha ha, caught another one!',
	'Sorry, I\'m on duty, Mr. Freeman.',
	':3',
	'Hey, Mr. Freeman, I had a bunch of messages for you but we had a system crash about 20 minutes ago and I\'m still trying to find my files. Just one of those days I guess. They were having some problems down in the test chamber too, but I think that\'s all straightened out. They told me to make sure you headed down there as soon as you got into your hazard suit.',
	'Good morning and welcome to the Black Mesa Transit system',
	"Welcome to Half-Life 2, Episode 2. We are at the mid-point in our trilogy of episodes which will conclude in Episode 3. To listen to a commentary node, put your crosshair over the floating commentary symbol and press your use key. To stop a commentary node, put your crosshair over the rotating node and press the use key again. Some commentary nodes may take control of the game in order to show something to you. In these cases, simply  press your use key again to stop the commentary. Please let me know what you think after you've had a chance to play this. I can be reached at gaben@valvesoftware.com, I get about 10,000 emails each time we release a game, and while I can't respond to all of them, I do read all of them. Thanks, and have fun!",
	'Alt+] or alt+u selects an image, alt+] or alt+i sends the image',
	'Pressing period when the textbox is not selected toggles autoscroll',
	"I don't even know whose peanut butter it was! I was hungry and there was peanut butter!",
	"15 Seconds of Bora! (YEAH!)",
	"Maybe the real Bad Place were the friends we made along the way.",
	"Bortles!",
	"Oh dip!",
	"My name is Zubin and I can swim!!!",
	"Hit the whip!",
	"It's peanut butter jelly time!",
	"This sentence is false.",
	"So there's this man, he has a time machine. Up and down history he goes, zip, zip, zip, zip, zip, getting into scrapes. Another thing he has is a a passion for the works of Ludwig van Beethoven. And one day he thinks, 'What's the point of having a time machine if you don't get to meet your heroes?' So off he goes to 18th century Germany, but he can't find Beethoven anywhere. No one's heard of him. Not even his family have any idea who the time traveller is talking about. Beethoven literally... doesn't exist. This didn't happen by the way. I've met Beethoven. Nice chap, very intense. Loved an arm wrestle. No, this is called the bootstrap paradox. Google it. The time traveller panics. He can't bear the thought of a world without the music of Beethoven. Luckily he brought all of his Beethoven sheet music for Ludwig to sign. So he copies out all the concertos and the symphonies, and he gets them published. He becomes Beethoven. And history continues with barely a feather ruffled. But my question is this - who put those notes and phrases together? Who really composed Beethoven's 5th?",
  "Don't forget to click below to subscribe to the official Doctor Who YouTube channel",
	`${Math.floor(Math.random() * 10000)} is your lucky number`,
	"I might rap like an english chap",
	"Hey ho, don't cha know, it's a good old fashion puppet show, thats right quite the set, it's the marionette quintet",
	"Ah, Hello Gordon!",
	"Another day another dollar!", //thats what we say here at the black mesa research facility! Ha ha!
	"I drink soda for lunch",
	"Why do we have to all wear these ridiculous ties?!",
	"Do you know who ate all the donuts?",
	"Have you seen my coffee cup?",
  "Stop fucking with the microwave!",
  '"Who is Gordon?" - Rey',
  'Part one.',
  'Part two.',
  'Part three.',
  "I ever tell you about the time me and Keith made a homemade bumper car ride with   ridin' mowers in his backyard? Mower blade wounds over 90% of his body.",
  "I ever tell you about the time my buddy Keith drowned in the Tunnel of Love? You   wouldn't think it could happen 'cause the water's so shallow, but that's how it     gets you, man. Overconfidence. Keith was with his lady at the time, and he was      yellin' for her to save him, but she didn't want to get wet.",
  `I ever tell you about the time Keith and I made fireworks? Now, I didn't know   shit about chemistry, but Keith figured "Gasoline burns, doesn't it?" Heh, third-  degree burns on 95 percent of his body.`,
  "I ever tell you about the time Keith tried to deep-fry a turkey? Third-degree   burns over 90 percent of his body.",
  "I ever tell you about the time my buddy Keith fell down an open manhole? He was unconscious down there for like a week.",
  "One time, the Army bombed my buddy Keith. He went camping and didn't bother to read the signs, and I guess they were just testing bombs that day.",
  "Yo, my buddy Keith had his car drop in a lake off a bridge just like this one here... Yeah, see, he was driving over it late at night and there in the middle of the bridge was what looked like, In Keith's estimation, like a dead bear, so Keith gets out his car to find a stick to poke at it, right? Well, it turns out it's just some lady's fur coat that musta fallen out her car, so, hey, free coat, right? Now, owls won't normally attack a man, but in this case, they were hungry, and that made them reckless, man. Keith reckons that they musta been there for hours watchin' what they thought was a bear carcass, 'cause as soon as he picked it up, them owls had claws in him inch deep. Well, Keith figures his best bet is to jump in a lake, 'cause owls can't swim. Well, them owls could. He fought them for like 20 minutes treading water, and during that time, a boat came, the bridge went up and down went Keith's car. Man, sometimes nature's just tryin' to teach us, if we'd only listen.",
  
	
];
const tommyVoice = [
	"Right, very carefully, slower than molasses drips off a spoon. :)",
	"I'm an orphan, but I have a dog!",
	"When it's L-...purple, like the evening, of a spring evening, then it means he's okay.",
	"I'm always squeezing the trigger! Should I not be do that-? …doing that?",
	"It's all- this is all mechanically necessary!" ,
	"They don't- There's no article about that on Wikipedia, the free encyclopedia!",
	"I drink soda for lunch!",
	"Mr. Freeman! Be careful! More careful... than a badger going after a... a den of snakes!",
	"Black Mesa makes ALL the Powerade™!",
	"This is all instinct, Mr. Freeman! I'm scared!",
	"I can recognize Beyblades when I see 'em!",
	"Yup! And it's all built to code. The U.S. lets us do this. This is all to regulation. Everything.",
	"This is all built to CODE!! It'll be okay.",
	"When we get outta here I'm gonna write the Wikipedia article for the the uh the Black Mesa Golem Ape!",
	"Grab a soda, Mr. Freeman! It'll help you see faster!" ,
	
];
function refreshSplash(){
	//Display the splashtext
	if(rightNow.getUTCMonth() == 3 && rightNow.getUTCDay() == 1){
		textBox.placeholder = tommyVoice[Math.floor(Math.random() * tommyVoice.length)];
		return;
	}
	
	textBox.placeholder = splashText[Math.floor(Math.random() * splashText.length)];
}
refreshSplash();